version: '3.7'

services:
  lanchonete:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/src
    working_dir: /app/src
    environment:
      - MONGODB_CONNECTION_STRING_PEDIDO=${MONGODB_CONNECTION_STRING_PEDIDO}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    networks:
      - default

networks:
  default:
    name: lanchonete_pedido_network
