version: '3.7'

services:
  lanchonete:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/src
    working_dir: /app/src
    environment:
      - MONGODB_CONNECTION_STRING_PEDIDO=${MONGODB_CONNECTION_STRING_PEDIDO}
    networks:
      - default

networks:
  default:
    name: lanchonete_pedido_network
