apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pedido-app
  template:
    metadata:
      labels:
        app: pedido-app
    spec:
      containers:
        - name: pedido-app
          image: danilocassola/fiap-lanchonete-pedido:v1.4
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
          env:
            - name: MONGODB_CONNECTION_STRING_PEDIDO
              valueFrom:
                secretKeyRef:
                  name: pedido-app-secrets
                  key: MONGODB_CONNECTION_STRING_PEDIDO
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: pedido-app-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pedido-app-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pedido-app-secrets
                  key: AWS_SESSION_TOKEN
